apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition

metadata:
  name: appdeployments.platform.cloudnative.dev

spec:
  group: platform.cloudnative.dev

  scope: Namespaced

  names:
    plural: appdeployments
    singular: appdeployment
    kind: AppDeployment
    shortNames:
      - appdeploy

  versions:
    - name: v1alpha1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object

          properties:
            spec:
              type: object

              required:
                - image
                - replicas
                - port

              properties:
                image:
                  type: string

                replicas:
                  type: integer
                  format: int32
                  minimum: 1

                port:
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 65535